name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Build with Maven
      #run: mvn -B package --file pom.xml
      run: mvn -B clean test install -DskipTests
    - id: getfilename
      run: echo "::set-output name=file::$(ls target/symphony-dal-infrastructure-management-crestron-xio.jar)"
    - uses: actions/upload-artifact@v1
      with:
        name: CrestronXiO
        path: ${{ steps.getfilename.outputs.file }}
